### Elementos basicos de Python
### Edgar Acuna, Math Department, UPR-Mayaguez
### Octubre, 2018

In [54]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<type 'numpy.ndarray'>
(3L,)
(1, 2, 3)
[5 2 3]
(2L, 3L)
(1, 2, 4)


In [55]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]


In [62]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print b


[[2 3]
 [6 7]]


In [63]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
b

array([[2, 3],
       [6, 7]])

In [67]:
#Halla los elementos de a que son mayores que 2
bool_idx = (a > 2)   
print(bool_idx)     
#Imprime un arregglo con los valores de a que son mayores que 2  
print(a[a > 2]) 

[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 3  4  5  6  7  8  9 10 11 12]


In [69]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [73]:
print(x * y)
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [76]:
import pandas as pd
import numpy as np
data = np.array([8,11,21,13])
s = pd.Series(data)
print s

0     8
1    11
2    21
3    13
dtype: int32


In [77]:
print  s[0]

8


In [78]:
s.mean()

13.25

In [80]:
s.median()

12.0

In [85]:
s.var()

30.916666666666668

In [89]:
import pandas as pd
data = [['Renato',19],['Paolo',16],['Camila',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print df

     Name  Age
0  Renato   19
1   Paolo   16
2  Camila   13


In [91]:
data = {'Name':['Renato', 'Paolo', 'Camila'],'Age':[19,16,13]}
df = pd.DataFrame(data)
print df

   Age    Name
0   19  Renato
1   16   Paolo
2   13  Camila


In [92]:
d = {'edad' : pd.Series([19, 16, 13]),
      'name' : pd.Series(['Renato', 'Paolo', 'Camila', 'Elena'])}

df = pd.DataFrame(d)
print df

   edad    name
0  19.0  Renato
1  16.0   Paolo
2  13.0  Camila
3   NaN   Elena
